ManageCashOfHomeDemo/Controllers/BankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using myApp.Models;
using myApp.Models.Reopsitory;
using System.Net.Http;

namespace ManageCashOfHomeDemo.Controllers
{
    public class BankController : Controller
    {

        HttpClient client = new HttpClient();

        BankRepository repository = null;

        public BankController()
        {
            repository = new BankRepository();
        }

        public ActionResult FirstPage()
        {
            return View();
        }

        public ActionResult AddBranch()
        {

            return View();
        }

        [HttpPost]
        public ActionResult AddBranch(BranchModel model)
        {
            BranchModel data = repository.addBranch(model);

            if (data != null)
            {
                ModelState.Clear();
                ViewBag.isSuceess = "Branch Added Successfully....";
            }
            return RedirectToAction("BranchList");
        }

        public ActionResult AddAccount()
        {
            AccountModel model = new AccountModel();

            model.UserList = repository.UserNameDropDown();
            model.BranchList = repository.BranchNameDropDown();

            return View(model);
        }

        [HttpPost]
        public ActionResult AddAccount(AccountModel model)
        {
            if (ModelState.IsValid)
            {
                AccountModel data = repository.addAccount(model);

                if (data != null)
                {
                    ModelState.Clear();
                    ViewBag.success = "User Account Is Added.....";
                }
            }
            return RedirectToAction("AccountList");
        }

        public ActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Register(UserModel model)
        {
            if (ModelState.IsValid)
            {
                //int id = repository.RegisterNewUser(model);
                //if (id > 0)

                client.BaseAddress = new Uri("https://localhost:44324/api/BankApi/insertImage/");
                var responce = client.PostAsJsonAsync<UserModel>("BankApi", model);
                responce.Wait();

                var test = responce.Result;

                if (test.IsSuccessStatusCode)
                {
                    ModelState.Clear();
                    ViewBag.isSuceess = "User Successfully Registered.....!!";
                }

                UserModel data = repository.RegisterNewUser(model);

                if (data != null)
                {
                    ModelState.Clear();
                    ViewBag.isSuceess = "User Successfully Registered.....!!";
                }

            }
            return View();
        }

        public ActionResult Login()
        {
            return View();

        }

        [HttpPost]
        public ActionResult Login(LoginModel model)
        {

            UserModel data = repository.UserLogin(model.email, model.password);

            if (ModelState.IsValid)
            {
                if (data.id != 0)
                {
                    FormsAuthentication.SetAuthCookie(model.email, false);
                    return RedirectToAction("FirstPage");
                }
                else
                {
                    ViewBag.isFailure = "Login Failed.....!!";
                    //ModelState.AddModelError("Failure", "Wrong Username and password combination !");
                    return View();
                }
            }
            else
            {
                return View(model);
            }
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            Session.Abandon(); // it will clear the session at the end of request
            return RedirectToAction("Login");
        }

        //public ActionResult BranchList()
        //{
        //    List<BranchModel> result = repository.BranchDetailsList();
        //    return Json(result);
        //}
        [HttpGet]
        public ActionResult BranchList()
        {
            //List<BranchModel> result = repository.BranchDetailsList();
            //return Json(result);
            return View();
        }

        [HttpPost]
        public JsonResult BranchList(BranchModel model)
        {
            var result = repository.BranchDetailsList();
            return Json(result);
        }

        public ActionResult EditBranchDetails(int id)
        {
            BranchModel objBranchModel = repository.getBranchById(id);
            return View(objBranchModel);
        }

        [HttpPost]
        public ActionResult EditBranchDetails(BranchModel model)
        {
            if (ModelState.IsValid)
            {
                repository.UpdateBranchDetails(model.branchid, model);
                return RedirectToAction("BranchList");
            }
            return View();
        }

        public ActionResult DeleteBranch(int id)
        {
            repository.deleteBranch(id);
            return RedirectToAction("BranchList");
        }
        
        public ActionResult AccountList()
        {
            List<AccountModel> list = repository.accountDetailsList();
            return View(list);
        }

        public ActionResult EditAccountDetails(int id)
        {
            AccountModel objAccountModel = repository.getAccountById(id);
            return View(objAccountModel);
        }

        [HttpPost]
        public ActionResult EditAccountDetails(AccountModel model)
        {
            if (ModelState.IsValid)
            {
                repository.UpdateAccountDetails(model.id, model);
                return RedirectToAction("AccountList");
            }
            return View();
        }

        public ActionResult DeleteAccount(int id)
        {
            repository.deleteAccount(id);
            return RedirectToAction("AccountList");
        }
    }
}

ManageCashOfHomeDemo/Controllers/TransactionController.cs
using myApp.Models;
using myApp.Models.Reopsitory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ManageCashOfHomeDemo.Controllers
{
    public class TransactionController : Controller
    {
        BankRepository repository = null;

        public TransactionController()
        {
            repository = new BankRepository();
        }

        public ActionResult Index()
        {
            TransactionModel model = new TransactionModel();
            model.accountList = repository.accountNumberDropDown();

            return View(model);
        }

        [HttpPost]
        public ActionResult Index(TransactionModel model)
        {

            if (ModelState.IsValid)
            {
                 model.CashTransaction.Count = CashNoteCount(
                    model.CashTransaction.C100,
                    model.CashTransaction.C200,
                    model.CashTransaction.C500,
                    model.CashTransaction.C2000
                    );

                bool compareAmount = CashNoteCount(
                    model.CashTransaction.C100,
                    model.CashTransaction.C200,
                    model.CashTransaction.C500,
                    model.CashTransaction.C2000,
                    model.amount.Value
                    );       

                if (compareAmount == true)
                {
                    model.Account = repository.getAccountById(model.accountId.Value);

                    if (model.amount >= model.Account.withdrawLimit)
                    {
                        ViewBag.limitError = "You Can Not Withdrawl This Much Money";
                        model.accountList = repository.accountNumberDropDown();
                        return View(model);
                    }

                    if (model.Account.balance < model.Account.minBalance) {
                        ViewBag.minBalamceErr = "Warning.. Your Account Balnance is Very Less";
                        model.accountList = repository.accountNumberDropDown();
                        return View(model);
                    }

                    TransactionModel data = repository.transaction(model);
                    return RedirectToAction("TransactionList");
                }
                else
                {
                    ViewBag.message = "Your Amount Does Not Matches With The Note Count";
                    model.accountList = repository.accountNumberDropDown();
                }
            }

            return View(model);
        }


        [NonAction]
        public int CashNoteCount(int C100, int C200, int C500, int C2000)
        {
            return C100 + C200 + C500 + C2000;
        }   

        [NonAction]
        public bool CashNoteCount(int C100, int C200, int C500, int C2000,int amount)
        {
            int TotalAmount = ((C100 * 100) + (C200 * 200) + (C500 * 500) + (C2000 * 2000));
            if(TotalAmount == amount)
            {
                return true;
            }
            return false;
        }

        public ActionResult TransactionList()
        {

            List<TransactionModel> list = repository.transactionDetailsList();

            return View(list);

        }

    }
}

ManageCashOfHomeDemo/Views/Bank/AccountList.cshtml
@model IEnumerable<myApp.Models.AccountModel>

@{
    ViewBag.Title = "AccountList";
}

@if (Request.IsAuthenticated)
{

    <h3><b style="color:brown">Account List</b></h3>

    <input type="button" value="Add Account" onclick="@("window.location.href='" + @Url.Action("AddAccount", "Bank") + "'");" />

    <table class="table" id="AllTech">
        <thead>
            <tr>
                @*<th>
                    @Html.DisplayNameFor(model => model.userId)
                </th>*@
                <th>
                    @Html.DisplayNameFor(model => model.accountNumber)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.User.fullName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Branch.branchName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.minBalance)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.withdrawLimit)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.balance)
                </th>
                @*<th>
                    @Html.DisplayNameFor(model => model.branchId)
                </th>*@
                <th></th>
            </tr>
        <thead>

        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.userId)
                    </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.accountNumber)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.User.fullName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Branch.branchName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.minBalance)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.withdrawLimit)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.balance)
                    </td>
                    @*<td>
                        @Html.DisplayFor(modelItem => item.branchId)
                    </td>*@
                    <td>
                        @Html.ActionLink("Edit", "EditAccountDetails", new { id = item.id }) |
                        @*@Html.ActionLink("Details", "Details", new { id = item.id }) |*@
                        @Html.ActionLink("Delete", "DeleteAccount", new { id = item.id, item.accountNumber, item.userId, item.minBalance, item.withdrawLimit, item.balance, item.branchId })
                    </td>
                </tr>

            }
        </tbody>
    </table>
    <div>
        @Html.ActionLink("Home", "FirstPage")
    </div>

}

@*<script src="../../Scripts/jquery-3.3.1.min.js"></script>*@
<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script src="~/Scripts/jquery.dataTables.min.js"></script>
<link href="~/Content/jquery.dataTables.css" rel="stylesheet" />

@*<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>*@
@*<link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css" rel="stylesheet" type="text/css" />*@

<script>
    $(document).ready(function () {
        $('#AllTech').DataTable();
    })
</script>

ManageCashOfHomeDemo/Views/Bank/AddAccount.cshtml
@model myApp.Models.AccountModel

@{
    ViewBag.Title = "AddAccount";
}

@if (Request.IsAuthenticated)
{
    <h3><b style="color:brown">Add Account</b></h3>

    using (Html.BeginForm("AddAccount", "Bank", FormMethod.Post))
    {
        <span><b>Select User</b>&nbsp</span>@Html.DropDownListFor(model => model.id, new SelectList(Model.UserList, "id", "fName"), "User Name")
        <br />
        <br />
        <span><b>Select Branch Name</b>&nbsp</span>@Html.DropDownListFor(model => model.branchId, new SelectList(Model.BranchList, "branchid", "branchName"), "Branch Name")
        <br />
        <br />
        using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                @Html.LabelFor(model => model.accountNumber, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.accountNumber, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.accountNumber, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.minBalance, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.minBalance, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.minBalance, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.withdrawLimit, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.withdrawLimit, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.withdrawLimit, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.balance, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.balance, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.balance, "", new { @class = "text-danger" })
                </div>
            </div>
            <input type="submit" value="AddAccount" />
            @ViewBag.isSuceess
        }
    }

    <br />

    <div>
        @Html.ActionLink("Account List", "AccountList")
    </div>
    <div>
        @Html.ActionLink("Home", "FirstPage")
    </div>

}

ManageCashOfHomeDemo/Views/Bank/AddBranch.cshtml
@model myApp.Models.BranchModel

@{
    ViewBag.Title = "AddBranch";
}

@if (Request.IsAuthenticated)
{

    <h3><b style="color:brown">Add Branch</b></h3>

    using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.branchNum, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.branchNum, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.branchNum, "", new { @class = "text-danger" })
                </div>
            </div>

            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.branchName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.branchName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.branchName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Add Branch" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Branch List", "BranchList")
    </div>

    <div>
        @Html.ActionLink("Home", "FirstPage")
    </div>

}

ManageCashOfHomeDemo/Views/Bank/BranchList.cshtml
@model IEnumerable<myApp.Models.BranchModel>


@{
    ViewBag.Title = "BranchList";
}


@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <style type="text/css">
        body {
            /*color: #4CAF50;*/
            font-size: 20px;
            margin-top: 22px;
            font-weight: 600;
        }

        hari {
            text-decoration: none;
        }
    </style>
</head>
<body style="padding-top:10px; ">


    <div style="width: 80%; margin-left:100px">
        @*<button type="button" class="btn navbar-btn hari">
                @Html.ActionLink("Back to Home", "Index")
            </button>*@
        <br />
        <table id="tblCustomers" cellpadding="2" cellspacing="0" border="1" style="margin-top:20px; border:1px solid " class="table-striped table-hover">

            <thead>
                <tr>
                    <th>Branch Number</th>
                    <th>Branch Name</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>

    @*<script src="../../Scripts/jquery-3.4.1.min.js"></script>*@
    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    @*<script type="text/javascript" src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js"></script>*@


    @*<link href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.css" rel="stylesheet" type="text/css" />*@

    <script src="~/Scripts/jquery.dataTables.min.js"></script>
    <link href="~/Content/jquery.dataTables.css" rel="stylesheet" />

    <script type="text/javascript">
        $(function () {
            $.ajax({
                type: "POST",
                url: "/Bank/BranchList",
                data: '{}',
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: OnSuccess,
                failure: function (response) {
                    alert(response.d);
                },
                error: function (response) {
                    alert(response.d);
                }
            });
        });
        function OnSuccess(response) {
            $("#tblCustomers").DataTable(
                {
                    bLengthChange: true,
                    lengthMenu: [[5, 10, 25, -1], [5, 10, 25, "All"]],
                    bFilter: true,
                    bSort: true,
                    bPaginate: true,
                    data: response,
                    columns: [
                        { 'data': 'branchNum' },
                        { 'data': 'branchName' },
                    ]
                });
        };
    </script>
</body>
</html>

ManageCashOfHomeDemo/Views/Bank/EditAccountDetails.cshtml
@model myApp.Models.AccountModel

@{
    ViewBag.Title = "EditAccountDetails";
}

<h3><b style="color:brown">EditAccountDetails</b></h3>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.userId)

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.branchId)
    @*<div class="form-group">
            @Html.LabelFor(model => model.userId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userId, "", new { @class = "text-danger" })
            </div>
        </div>*@
    <div class="form-group">
        @Html.LabelFor(model => model.User.fName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <span>@Model.User.fName</span>
            <br />
            @*<span>@Model.Branch.branchName</span>*@
            @*@Html.LabelFor(model => model.User.fName, new { htmlAttributes = new { @class = "form-control" } })*@
        </div>
    </div>                                                                  

    <div class="form-group">
        @Html.LabelFor(model => model.Branch.branchName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <span>@Model.Branch.branchName</span>
            @*@Html.LabelFor(model => model.User.fName, new { htmlAttributes = new { @class = "form-control" } })*@
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.accountNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.accountNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.accountNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.minBalance, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.minBalance, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.minBalance, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.withdrawLimit, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.withdrawLimit, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.withdrawLimit, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.balance, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.balance, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.balance, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<div class="form-group">
            @Html.LabelFor(model => model.branchId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.branchId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.branchId, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Edit" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Account List", "AccountList")
</div>

ManageCashOfHomeDemo/Views/Bank/EditBranchDetails.cshtml
@model myApp.Models.BranchModel

@{
    ViewBag.Title = "EditBranchDetails";
}

<h3><b style="color:brown">Edit Branch Details</b></h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.branchid)

    <div class="form-group">
        @Html.LabelFor(model => model.branchNum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.branchNum, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.branchNum, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.branchName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.branchName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.branchName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>

</div>
}

<div>
    @Html.ActionLink("Back To List", "BranchList")
</div>

ManageCashOfHomeDemo/Views/Bank/FirstPage.cshtml
@{
    ViewBag.Title = "FirstPage";
}

<h2>BankApp</h2>


@if (Request.IsAuthenticated)
{
    <span>Welcome - <b style="color:green"> @Html.Encode(User.Identity.Name) </b></span>
    <br />
    <br />


    <input type="button" value="Branch" onclick="@("window.location.href='" + @Url.Action("BranchList", "Bank") + "'");" />

    <input type="button" value="Account" onclick="@("window.location.href='" + @Url.Action("AccountList", "Bank") + "'");" />

    <input type="button" value="Transaction List" onclick="@("window.location.href='" + @Url.Action("TransactionList", "Transaction") + "'");" />


    <p style="color:green">@ViewBag.success</p>
}

ManageCashOfHomeDemo/Views/Bank/Login.cshtml
@model myApp.Models.LoginModel

@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
        </div>
    </div>

    @*<b style="color:red">@ViewBag.AddModelError</b>*@

    <b style="color:red">@ViewBag.isFailure</b>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Login" class="btn btn-default" id="lbtn" style="background-color:lawngreen" />
            <input type="button" value="Register" onclick="@("window.location.href='" + @Url.Action("Register", "Bank") + "'");" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Register New User", "Register", "Bank")
</div>